In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [5]:
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [19]:
s['b'] # first way
s[['a', 'c']] # second way
s[s > 0] # third way

a    1
b    2
c    3
d    4
dtype: int64

In [21]:
boolenArray = s > 1
boolenArray

a    False
b     True
c     True
d     True
dtype: bool

In [24]:
s[boolenArray]

b    2
c    3
d    4
dtype: int64

In [41]:
df = pd.DataFrame([1, 2, 3], columns=['numbers'])
df

   numbers
0        1
1        2
2        3

In [44]:
df = pd.DataFrame({'Fruits': ['Apple', 'Banana', 'Cherry'], 'Vehicles': ['Bike', 'Car', 'Truck']})
df

   Fruits Vehicles
0   Apple     Bike
1  Banana      Car
2  Cherry    Truck

In [2]:
elections = pd.read_csv('/kaggle/input/elections-csv/elections.csv')
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [66]:
elections.loc[[5, 10, 15], ['Candidate', 'Year', 'Result']]

           Candidate  Year Result
5         Henry Clay  1832   loss
10  Martin Van Buren  1840   loss
15  Martin Van Buren  1848   loss

In [67]:
elections.loc[[5, 10, 15], 'Candidate': 'Result']

           Candidate                Party  Popular vote Result
5         Henry Clay  National Republican        484205   loss
10  Martin Van Buren           Democratic       1128854   loss
15  Martin Van Buren            Free Soil        291501   loss

In [5]:
elections.loc[20 : 27, 'Year':'%']

,Year,Candidate,Party,Popular vote,Result,%
20,1856,James Buchanan,Democratic,1835140,win,45.306080
21,1856,John C. Frémont,Republican,1342345,loss,33.139919
22,1856,Millard Fillmore,American,873053,loss,21.554001
23,1860,Abraham Lincoln,Republican,1855993,win,39.699408
24,1860,John Bell,Constitutional Union,590901,loss,12.639283
25,1860,John C. Breckinridge,Southern Democratic,848019,loss,18.138998
26,1860,Stephen A. Douglas,Northern Democratic,1380202,loss,29.522311
27,1864,Abraham Lincoln,National Union,2211317,win,54.951512

In [3]:
# 7. Bonus Challenge
# • Create a new column called 'Vote Margin' that calculates the difference in votes between the candidate
# and the average popular vote for that election year. 
# Then, display the top 5 candidates with the largest vote margin.


# elections.loc[elections['Candidate']=='Andrew Jackson']
# print(elections.dtypes)

gk = elections.groupby(elections['Year'])
avg_vote = gk['Popular vote'].mean()
# print(avg_vote)

# elections[['Year', 'Popular vote']]

elections['Average vote'] = elections['Year'].map(avg_vote)
elections['Vote Margin'] = abs(elections['Average vote'] - elections['Popular vote'])
sort_margin = elections.sort_values('Vote Margin', ascending=False)
sort_margin.head(5)

# avg_vote[elections['Year']] - elections['Year']
# elections['Year']

# year_sort = elections.sort_values('Year')
# year_sort
# gk = elections.groupby('Year')
# gk.get_group(1856)
# dic = {}
# elections[['Popular vote', 'Result']]

,Year,Candidate,Party,Popular vote,Result,%,Average vote,Vote Margin
162,2008,Barack Obama,Democratic,69498516,win,53.023510,2.184519e+07,4.765333e+07
176,2016,Hillary Clinton,Democratic,65853514,loss,48.521539,2.262003e+07,4.323349e+07
178,2020,Joseph Biden,Democratic,81268924,win,51.311515,3.943896e+07,4.182996e+07
157,2004,George W. Bush,Republican,62040610,win,50.771824,2.036583e+07,4.167478e+07
173,2016,Donald Trump,Republican,62984828,win,46.407862,2.262003e+07,4.036480e+07